# Generated by Django 2.1.1 on 2018-09-18 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_user',
            options={'ordering': ('creation_time',)},
        ),
        migrations.AddField(
            model_name='blog_user',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
