# Generated by Django 2.1.1 on 2018-09-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180918_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_user',
            options={},
        ),
        migrations.AlterModelTable(
            name='blog_user',
            table=None,
        ),
    ]
